### ISSUE TITLE
Lab transform will insert multiple rows in new polyhierarchical ontology

### ISSUE THREAD

**Issue by jklann** [SCILHS/i2o-transform#6]
This line will cause multiple rows to be inserted per fact:

https://github.com/i2b2-omop/i2o-transform/blob/78083d31de64778325f48c168e484808c37b0196/MSSQL/OMOPLoader.sql#L1061

See issue [#74 in i2p-transform](https://github.com/ARCH-commons/i2p-transform/issues/74).

Short-term fix would be to rip out normal ranges until better solution can be implemented.

**Comment by matthewjoss** [comment]
I Have taken out the normal ranges and inserted null as a temporary fix. Still need a better solution.

**Comment by jklann** [comment]
Matt propagated the i2p change in commit f9b176aa5bb80a925a19ddc75e2d6a6e8922b2ee .
